//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetBI_DataGenerator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Acidofilo;2.31;3.42;0.23,Bouteille cola;2.99;4.43;0.3,Brazil pik;3.94;5.83;0.39,Color Schtroummpf pik;2.75;4.07;0.28,Langues acides;3.84;5.68;0.38,London pik;3.08;4.56;0.31,Miami pik;2.93;4.34;0.29,Pasta Basta;2.11;3.12;0.21,Pasta frutta;2.37;3.51;0.24,Sour snup;3.66;5.42;0.37,Dragibus;2.47;3.66;0.25,Carensac;2.05;3.03;0.21,Fraizibus;3.92;5.8;0.39,Grain de millet;2.16;3.2;0.22,Starmint;2.49;3.69;0.25,Florent violette;3.47;5.14;0.35,Kimono;3.92;5.8;0.39,Pain Zan;3.17;4.69;0.32,Rotella;2.27;3.36;0.23,Zanoïd;3.25;4.81;0.33,Fraise tagada;2.9;4.29;0.29,Croco;2.36;3.49;0.24,Chamallows;2.04;3.02;0.2,Polka;3.77;5.58;0.38,Banane;2.74;4.06;0.27,Ourson;3.59;5.31;0.36,Filament;3.99;5.91;0.4")]
        public string Types {
            get {
                return ((string)(this["Types"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Rouge,Orange,Jaune,Vert,Bleu,Violet,Noir,Marron")]
        public string Colors {
            get {
                return ((string)(this["Colors"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Acide,Sucré,Gélifié")]
        public string Variants {
            get {
                return ((string)(this["Variants"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mou,Dur")]
        public string Textures {
            get {
                return ((string)(this["Textures"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sachet,Boite,échantillon")]
        public string Conditioning {
            get {
                return ((string)(this["Conditioning"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Allemagne,Camion;Autriche,Camion;Belgique,Camion;Bulgarie,Camion;Chypre,Camion;Croatie,Camion;Danemark,Camion;Espagne,Camion;Estonie,Camion;Finlande,Camion;France,Camion;Grèce,Camion;Hongrie,Camion;Irelande,Camion;Italie,Camion;Lettonie,Camion;Lituanie,Camion;Luxembourg,Camion;Malte,Camion;Pays-Bas,Camion;Pologne,Camion;Portugal,Camion;République tchèque,Camion;Roumanie,Camion;Royaume-Uni,Camion;Slovaquie,Camion;Slovénie,Camion;Suède,Camion;USA,Avion;Canada,Avion;Mexique,Avion;Japon,Bateau;Chine,Avion;Afrique du sud,Bateau")]
        public string Countries {
            get {
                return ((string)(this["Countries"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\part.csv")]
        public string PartCSVPath {
            get {
                return ((string)(this["PartCSVPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\order.csv")]
        public string OrderCSVPath {
            get {
                return ((string)(this["OrderCSVPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public int MaxOrderParts {
            get {
                return ((int)(this["MaxOrderParts"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2017-05-01")]
        public global::System.DateTime StartDate {
            get {
                return ((global::System.DateTime)(this["StartDate"]));
            }
        }
    }
}
