//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetBI_DataGenerator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Acidofilo,Bouteille cola,Brazil pik,Color Schtroummpf pik,Langues acides,London pik,Miami pik,Pasta Basta,Pasta frutta,Sour snup,Dragibus,Carensac,Fraizibus,Grain de millet,Starmint,Florent violette,Kimono,Pain Zan,Rotella,Zanoïd,Fraise tagada,Croco,Chamallows,Polka,Banane,Ourson,Filament")]
        public string Types {
            get {
                return ((string)(this["Types"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Rouge,Orange,Jaune,Vert,Bleu,Violet,Noir,Marron")]
        public string Colors {
            get {
                return ((string)(this["Colors"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Acide,Sucré,Gélifié")]
        public string Variants {
            get {
                return ((string)(this["Variants"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mou,Dur")]
        public string Textures {
            get {
                return ((string)(this["Textures"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sachet,Boite,échantillon")]
        public string Conditioning {
            get {
                return ((string)(this["Conditioning"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Allemagne,Camion;Autriche,Camion;Belgique,Camion;Bulgarie,Camion;Chypre,Camion;Croatie,Camion;Danemark,Camion;Espagne,Camion;Estonie,Camion;Finlande,Camion;France,Camion;Grèce,Camion;Hongrie,Camion;Irelande,Camion;Italie,Camion;Lettonie,Camion;Lituanie,Camion;Luxembourg,Camion;Malte,Camion;Pays-Bas,Camion;Pologne,Camion;Portugal,Camion;République tchèque,Camion;Roumanie,Camion;Royaume-Uni,Camion;Slovaquie,Camion;Slovénie,Camion;Suède,Camion;USA,Avion;Canada,Avion;Mexique,Avion;Japon,Bateau;Chine,Avion;Afrique du sud,Bateau")]
        public string Countries {
            get {
                return ((string)(this["Countries"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\part.csv")]
        public string PartCSVPath {
            get {
                return ((string)(this["PartCSVPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\order.csv")]
        public string OrderCSVPath {
            get {
                return ((string)(this["OrderCSVPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public int MaxOrderParts {
            get {
                return ((int)(this["MaxOrderParts"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2017-05-01")]
        public global::System.DateTime StartDate {
            get {
                return ((global::System.DateTime)(this["StartDate"]));
            }
        }
    }
}
